server:
  port: ${server_port:1999}
spring:
  profiles:
    active: test
  application:
    name: gift-shop
  mail:
    host: smtp.sendgrid.net
    port: 25
    ssl: no
    tls: yes
    username: apikey
    password: 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
    protocol: smtp

# JTW Config
jwt:
  secret: ${jwt_secret:thisisathirtycharacterlongstring}
  expiration: 3600000

google:
  CLIENT_ID: 120787335948-g4r6bof29ub3vaaaiu7pc01jd5dalooq.apps.googleusercontent.com

facebook:
  TOKEN_VALIDATION_URL: https://graph.facebook.com/me?access_token=
